### ISSUE TITLE
Can't install using Plugin manager

### ISSUE THREAD

**Issue by eugenov** [moemoechu/tabby-highlight#1]
Hello!
Once I try to install - I get following error:
![изображение](https://github.com/moemoechu/tabby-highlight/assets/61651148/49cc4bb2-f9f7-4371-bc0b-c561b11bd49b)
Tabby 1.0.204 Portable

**Comment by moemoechu** [comment]
I tried in a new unzipped protable 1.0.204 in windows , and the problem is not represent, can you provide logs in DevTools?
