### ISSUE TITLE
Could you show an example of using RegEx?

### ISSUE THREAD

**Issue by MohammedNoureldin** [moemoechu/tabby-highlight#11]
Hi, I have been trying to use the RegEx, but for some reason I do not understand how this works.

For example, I wanted to match any word that has "succ" in the beginning. So the whole word should then be highlighted.

Like: succeed, succeeded, successful, etc.

For that, I used this RegEx: `succ.*`

But this does not work, actually no RegEx I tried worked at all. Could you please show a few examples how it can be used?

**Comment by moemoechu** [comment]
![image](https://github.com/moemoechu/tabby-highlight/assets/6707029/e615c0df-a85e-4909-a3d3-ba0dd57078db)
![image](https://github.com/moemoechu/tabby-highlight/assets/6707029/9ad207bb-dd06-4329-ab74-538aa2bda37d)

succ.* can match  succeed, succeeded, successful 
Please check whether (.*) is checked(green box in the screenshot)
and there are some example in this repo called [highlight_test_profile.json](https://github.com/moemoechu/tabby-highlight/blob/main/highlight_test_profile.json) you can download and import it.

**Comment by MohammedNoureldin** [comment]
Oh sorry for this, I just had to restart the software to make the changes effective.

Thank you for this great plugin!
