### ISSUE TITLE
Button "Add" (expression) does nothing...

### ISSUE THREAD

**Issue by eugenov** [moemoechu/tabby-highlight#12]
Since v. 2.0.1. Button "Add" (expression) has no effect...

**Comment by moemoechu** [comment]
cannot reproduce this problem, is there any error log on console when click the add button?

**Comment by moemoechu** [comment]
thats may be something wrong on that profile, maybe you can try export this profile then add a new profile and import the file.

**Comment by moemoechu** [comment]
maybe your profile is broken, it will be help to solve this problem if you can provide your plugin settings, or you can try delete this profile and start a new profile.
