### ISSUE TITLE
如何离线安装？

### ISSUE THREAD

**Issue by zodiacg** [moemoechu/tabby-highlight#13]
使用环境无法访问外网，没办法用插件管理器直接安装，请问如何手动离线安装插件？

**Comment by moemoechu** [comment]
2个办法，一个是安装node，然后执行npm run build，把生成的dist目录中的文件复制到插件目录的node_modules/tabby-highlight下，
二个是使用有外网的机器安装，然后从插件目录的node_modules下复制整个tabby-highlight过去。

**Comment by zodiacg** [comment]
```
ERROR in /home/zodiacg/tabby-highlight/src/settings-tab.component.ts
./src/settings-tab.component.ts 8:2-21
[tsl] ERROR in /home/zodiacg/tabby-highlight/src/settings-tab.component.ts(8,3)
      TS2724: '"tabby-core"' has no exported member named 'PartialProfileGroup'. Did you mean 'PartialProfile'?
 @ ./src/index.ts 20:0-73 40:26-55 41:23-52

ERROR in /home/zodiacg/tabby-highlight/src/settings-tab.component.ts
./src/settings-tab.component.ts 10:2-14
[tsl] ERROR in /home/zodiacg/tabby-highlight/src/settings-tab.component.ts(10,3)
      TS2614: Module '"tabby-core"' has no exported member 'ProfileGroup'. Did you mean to use 'import ProfileGroup from "tabby-core"' instead?
 @ ./src/index.ts 20:0-73 40:26-55 41:23-52

ERROR in /home/zodiacg/tabby-highlight/src/settings-tab.component.ts
./src/settings-tab.component.ts 119:52-68
[tsl] ERROR in /home/zodiacg/tabby-highlight/src/settings-tab.component.ts(119,53)
      TS2551: Property 'getProfileGroups' does not exist on type 'ProfilesService'. Did you mean 'getProfiles'?
 @ ./src/index.ts 20:0-73 40:26-55 41:23-52

3 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.89.0 compiled with 3 errors in 2154 ms
```
报了这样的错，我再试下不用latest的，实在不行晚上回去找台能用的机器拖……

**Comment by ihaoxiansheng** [comment]
> ```
> ERROR in /home/zodiacg/tabby-highlight/src/settings-tab.component.ts
> ./src/settings-tab.component.ts 8:2-21
> [tsl] ERROR in /home/zodiacg/tabby-highlight/src/settings-tab.component.ts(8,3)
>       TS2724: '"tabby-core"' has no exported member named 'PartialProfileGroup'. Did you mean 'PartialProfile'?
>  @ ./src/index.ts 20:0-73 40:26-55 41:23-52
> 
> ERROR in /home/zodiacg/tabby-highlight/src/settings-tab.component.ts
> ./src/settings-tab.component.ts 10:2-14
> [tsl] ERROR in /home/zodiacg/tabby-highlight/src/settings-tab.component.ts(10,3)
>       TS2614: Module '"tabby-core"' has no exported member 'ProfileGroup'. Did you mean to use 'import ProfileGroup from "tabby-core"' instead?
>  @ ./src/index.ts 20:0-73 40:26-55 41:23-52
> 
> ERROR in /home/zodiacg/tabby-highlight/src/settings-tab.component.ts
> ./src/settings-tab.component.ts 119:52-68
> [tsl] ERROR in /home/zodiacg/tabby-highlight/src/settings-tab.component.ts(119,53)
>       TS2551: Property 'getProfileGroups' does not exist on type 'ProfilesService'. Did you mean 'getProfiles'?
>  @ ./src/index.ts 20:0-73 40:26-55 41:23-52
> 
> 3 errors have detailed information that is not shown.
> Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
> 
> webpack 5.89.0 compiled with 3 errors in 2154 ms
> ```
> 
> 报了这样的错，我再试下不用latest的，实在不行晚上回去找台能用的机器拖……

和楼上报一样的错。。 请问作者这个要怎么解决呢？还有从Tabby插件外网直接下载显示 highlight中的错误[Object Object]这是为什么？

**Comment by moemoechu** [comment]
npm install之后，需要从tabby程序目录下拷贝最新的依赖，比如：cp -rf ../Tabby/resources/builtin-plugins/* ./node_modules/，然后就可以npm run build了。
下载问题这个不清楚，看tabby的issue里有下其他插件也有出现，目前来看有说和杀毒软件有关的，也有说和网络有关的。

**Comment by ihaoxiansheng** [comment]
![QQ_1722405319583](https://github.com/user-attachments/assets/04debb4d-271e-4ba1-a46c-6a04ef55c480)
没有resources/builtin-plugins这个文件夹是什么问题？

**Comment by moemoechu** [comment]
mac的话，可以看下/Applications/Tabby.app/Contents/Resources/builtin-plugins

**Comment by ihaoxiansheng** [comment]
> mac的话，可以看下/Applications/Tabby.app/Contents/Resources/builtin-plugins

收到 已成功安装 感谢作者
