### ISSUE TITLE
Tabby 安装报错

### ISSUE THREAD

**Issue by L-Super** [moemoechu/tabby-highlight#14]
![image](https://github.com/moemoechu/tabby-highlight/assets/40905056/8c4dbd59-eb6a-4c57-9410-d27dfc937c01)

我在安装插件时，提示该错误，不知道是哪边的问题

**Comment by moemoechu** [comment]
应该是设置过什么npm镜像吧，可以试试换回默认的npm地址。

**Comment by L-Super** [comment]
> 应该是设置过什么npm镜像吧，可以试试换回默认的npm地址。

确实是npm淘宝镜像导致的
