### ISSUE TITLE
[Help] RegEx with case insensitive

### ISSUE THREAD

**Issue by pidgeon777** [moemoechu/tabby-highlight#15]
Hello, this is a test regex:

```regex
\bWORD(A(B)?)?\b
```

![image](https://github.com/moemoechu/tabby-highlight/assets/13739892/6e867516-dad3-4822-9531-9736b3eecc2c)

I'm trying to add case-insensitive flag to the regex in `tabby-highlight` so that even matches such as `wordA` or `WORdAb` can be highlighted, but I'm encountering difficulties, so I would kindly ask for help.

**Comment by moemoechu** [comment]
![image](https://github.com/moemoechu/tabby-highlight/assets/6707029/d5c4c60f-82a8-4a5d-9a9c-957e54efc5fc)
try check the Aa box, that's mean case sensitive.

**Comment by pidgeon777** [comment]
You're absolutely right.

I don't know why, but I thought that by checking the box, case-insensitive mode was enabled.

It seems that when checking the box, case-sensitive mode is enabled, instead.

Congratulations for having developed this plugin, though: it's extremely useful and adding a feature missing from most of the terminal emulators currently available 👍.
