### ISSUE TITLE
regex group match

### ISSUE THREAD

**Issue by pbartyik** [moemoechu/tabby-highlight#18]
It'd be nice to be able to match on regex groups as well, instead of the entire matched string.
This could be useful for remote session prompt highlighting, etc.

For example username highlight could be `\[(\w+)@\w+\s\w+\]` and it'd highlight the string `user` instead of the entire matched string in the string below. 

`[user@host ~]:`

Caveat being that regex does have other usecases for parentheses, for example: `([123]|[abc])?`

**Comment by pbartyik** [comment]
Thought on this a bit, and would make sense to treat the whole thing as match against groups. Default would be group 0 (the entire string as is now), additional options could specify a group(s).

**Comment by moemoechu** [comment]
try just released v2.3.0.

**Comment by pbartyik** [comment]
thanks, works great!
