### ISSUE TITLE
您的字体和图片是怎么设置的哇

### ISSUE THREAD

**Issue by bathIncense** [moemoechu/tabby-highlight#19]
可以发一下字体和背景嘛

**Comment by moemoechu** [comment]
字体在这：https://github.com/lxgw/kose-font
背景用[background](https://github.com/moemoechu/tabby-background)插件

**Comment by bathIncense** [comment]
感谢大佬指路谢谢.
        您好！


        有什么问题随时与我联系和沟通，期待您的回信，祝好！


2024-10-22
| |
抹茶沐浴焚香
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Cat in the orange ***@***.***> |
| 发送日期 | 2024年10月21日 16:39 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [moemoechu/tabby-highlight] 您的字体和图片是怎么设置的哇 (Issue #19) |

字体在这：https://github.com/lxgw/kose-font
背景用background插件
