### ISSUE TITLE
Highlight priority

### ISSUE THREAD

**Issue by eugenov** [moemoechu/tabby-highlight#2]
I have, for example, 5 regex expressions. What order of matching expressions is? From top at first to bottom as last or vice versa?

**Comment by moemoechu** [comment]
for now, the priority is form top to bottom, I will impliment some feature like reorder the keywords later.

**Comment by moemoechu** [comment]
I found there are some limitation in the highlight method based on control sequence, maybe I will look for a another solution.

**Comment by moemoechu** [comment]
Released version 1.1.0, possible fixed this issue.
