### ISSUE TITLE
高亮导致记录log时加入错误字符

### ISSUE THREAD

**Issue by randornot** [moemoechu/tabby-highlight#20]
Windows 10 企业版 LTSC 21H2

在Tabby中开启高亮的情况下
![image](https://github.com/user-attachments/assets/aba20111-afb6-4b79-8147-bd94a52a78fd)
使用save-output插件记录console打印日志到文件中，出现高亮文本的每个字符前面多出`;5;6m`的情况，原本高亮文本为`INFO`，保存输出到文件中会变为`;5;6mI;5;6mN;5;6mF;5;6mO`
**Tabby:**
![Tabby](https://github.com/user-attachments/assets/7cfb0e48-8544-46d7-bf8c-d5b77bd711ab)

**save-output to txt:**
![save-output_to_txt](https://github.com/user-attachments/assets/05ef551b-bbce-485f-9e8c-25fa7f065f49)

如果不开启高亮
![image](https://github.com/user-attachments/assets/e16a5dd8-3b59-43ef-a701-1e2ca6088f64)
就不会出现这个问题
![image](https://github.com/user-attachments/assets/2a295f06-2dfb-4294-ae7a-57b11915277e)
麻烦帮忙分析一下是什么原因？

**Comment by moemoechu** [comment]
这个没办法，高亮的原理是通过在显示时插入xterm控制字符实现的，如果使用的日志记录插件没有去除控制字符的操作的话，这些控制字符就会被记录到日志里。

**Comment by randornot** [comment]
> 这个没办法，高亮的原理是通过在显示时插入xterm控制字符实现的，如果使用的日志记录插件没有去除控制字符的操作的话，这些控制字符就会被记录到日志里。

好那我了解了，谢谢
