### ISSUE TITLE
怎么去调色 我看15个颜色 都是差不多的颜色 红色这种怎么换呢

### ISSUE THREAD

**Issue by a576266** [moemoechu/tabby-highlight#5]
感谢插件  字体是啥啊  好看  看log里的错误 想换成亮色显眼一点

**Comment by moemoechu** [comment]
目前颜色是用的终端16色（跟随终端配色方案），后面有空会添加自定义颜色。
字体在这https://github.com/lxgw/kose-font

**Comment by a576266** [comment]
谢谢 不过我重新选择终端配色之后  16色还是无法改变
<img width="500" alt="BDADBB53-4DC4-46bd-94C5-25D09A90F71F" src="https://github.com/moemoechu/tabby-highlight/assets/69896813/2a45a3e6-b28e-425e-8bd2-ec08b041ed7f">
需要哪里清除一下吗

**Comment by moemoechu** [comment]
设置界面目前取的是暗黑模式的色彩，如果使用了亮色方案，虽然设置界面还是暗色的色彩，但实际终端内容是调整后的颜色
![image](https://github.com/moemoechu/tabby-highlight/assets/6707029/39dfddab-69d7-4dbf-8d4d-f4fda475959f)

**Comment by a576266** [comment]
明白了，搞定，多谢，希望你天天开心。
