### ISSUE TITLE
怎么设置ip地址高亮？

### ISSUE THREAD

**Issue by linusluo** [moemoechu/tabby-highlight#6]

**Comment by moemoechu** [comment]
高亮IP地址可以使用任何一个能匹配IP地址的正则即可，如IPv4可以用：
`(?:[0-9]{1,3}\.){3}[0-9]{1,3}`
![image](https://github.com/moemoechu/tabby-highlight/assets/6707029/d86bb9be-68d4-4bea-acf0-dea45f643b1e)
![image](https://github.com/moemoechu/tabby-highlight/assets/6707029/ad9a0421-e65a-48cd-8f6d-ff7e5b434fa2)

**Comment by catcherxuefeng** [comment]
`\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}(\/(\d){0,2})?`
