### ISSUE TITLE
可以只在串口会话上应用高亮吗?

### ISSUE THREAD

**Issue by catcherxuefeng** [moemoechu/tabby-highlight#7]
现在打开后是全局高亮,希望可以加入在不同会话自动启用不同的高亮配置

**Comment by moemoechu** [comment]
本来是想在会话配置里加一个选高亮方案的选择，但好像tabby没有接口可以直接在会话配置里加东西，有空的话，再看看有没有其他方案。

**Comment by moemoechu** [comment]
试试1.5.1版本，新增了按照会话、分组或者类型单独设定配置，但串口没有测试过。
