### ISSUE TITLE
Get errors while running "npm install"

### ISSUE THREAD

**Issue by bitto711** [moemoechu/tabby-highlight#8]
![CleanShot 2023-12-21 at 22 25 31](https://github.com/moemoechu/tabby-highlight/assets/110336973/f71b6e74-1262-4bc5-b7d4-0abaed18004e)

**Comment by bitto711** [comment]
大神，能否指导一下怎么装到Tabby for mac？谢谢
### Install
To install, use Tabby builtin plugin manager.

**Comment by moemoechu** [comment]
![image](https://github.com/moemoechu/tabby-highlight/assets/6707029/82ea014d-ad40-4306-b24b-e38ee4430bdb)
直接在插件里面装。。

**Comment by bitto711** [comment]
> ![image](https://private-user-images.githubusercontent.com/6707029/292233392-82ea014d-ad40-4306-b24b-e38ee4430bdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMDc5MzYsIm5iZiI6MTcwMzIwNzYzNiwicGF0aCI6Ii82NzA3MDI5LzI5MjIzMzM5Mi04MmVhMDE0ZC1hZDQwLTQzMDYtYjI0Yi1lMzhlZTQ0MzBiZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDExMzU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzRlOGUxNzhjMTk5ZDMyOGQyNzdiNzFkZGNjMTZiN2M2ODNkZDhhYmQ0MGE3ZjNmZDRhNTUwMGZmNjQ5ZDlmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vOVUr73ieWE38NvDn7RLXqYawJyjJeNVv5n4tXojCXA) 直接在插件里面装。。

![CleanShot 2023-12-22 at 09 15 12](https://github.com/moemoechu/tabby-highlight/assets/110336973/bc6495de-aaba-4467-8786-c66b2e0a9ad2)
安装完默认只有三种提示，要手动添加。其他的关键字例如时间戳、ip什么的都没有...能分享一下可导入的配置吗

**Comment by bitto711** [comment]
可以了。因为在Tabby里面装完，默认配置只有3种高亮关键字。

解决方案：导入highlight_test_profile.json即可。
