### ISSUE TITLE
Regex engine doesn't respect beginning of line (^)/end of line($)

### ISSUE THREAD

**Issue by eugenov** [moemoechu/tabby-highlight#9]
Hello!
First of all thank you for such useful plugin! It makes my life easier :)
The question is how I can match beginning of line and end of line expressions, as ^ and $ seems not working?
Thank you!

**Comment by moemoechu** [comment]
^ and $ not working because of there are some invisible control charactor in the terminal lines, i will looking for some method to handle it.

**Comment by moemoechu** [comment]
try the latest version v2.0.0

**Comment by moemoechu** [comment]
yeah ,that may be  something wrong of that plugin,
in fact i am planing to fork that plugin and do some modify.
